### ISSUE TITLE
Using Payfast gateway with other Simplecart example

### ISSUE THREAD

**Issue by keesmarcha** [PayFast/mod-simplecart#1]
I am 62 years old and my knowledge of javascript is very poor. I used your simplecart with the payfast gateway and it works fine but there is no shipping. I tried payfast helpdesk but they were unable to help or tell me where to get help to get the shipping working.
I got another simplecart example with shipping  and changed my pages with the new simplecart.js files. I used the script gateway to payfast but it only goes to paypal. I urgently need someone to help me sort the proplem out  I believe it will be something small for the person that did the original gateway script for payfast to change. It seems there is small differences within the two simplecart.js scripts.
I downloaded the example site from   http://www.html.it/articoli/simplecartjs-un-carrello-della-spesa-con-javascript-e-paypal-1/  . Is it possible to get the payfast scritpt to work with above example.  You can have a look at www.matrixkitchens.co.za where my files are uploaded. Like i said every thing works fine (Site still under construction) its just to get it to go to Payfast with the script you wrote for payfast.
Please if somebody can help I will really appreciate, Im am batling for over two months now and runs into deadends all over. I can Email all the files to anybody willing to look at them.

Thanks in advance  Kees Meyer

**Comment by andybeak** [comment]
Dear Kees,

I am a senior developer at Payfast.  You have reached my private email
address because it is linked to the Payfast repository that you are
struggling with.

We will be delighted to help you, but please email support@payfast.co.za so
that I can properly account for my time spent helping you (should I be
assigned to your ticket).

We are proud of a 24 hour turnaround and aim to get you up and running as
soon as possible.

Thank you for choosing Payfast.

Kind regards,
  Andy B
Developer

~a

Blog: http://abeak.blogspot.com/
Never mind saving trees by not printing this email... save the world in
your spare time (it's free) :
http://boinc.berkeley.edu/
http://stackoverflow.com/users/821275/andy

**Comment by TomFX** [comment]
Hi andybeak,
are you still a developer at payfast? I need some help setting up simplecart on my site. I want the cart to send shipping form email, and then send user to payfast for check out.

Can you possibly help, with example code or bit more info. I will really appreciate it

**Comment by andybeak** [comment]
Hi,

I no longer work for Payfast but they are generally quite willing to try
and help out.

You should try contacting their support desk and asking to speak to Nico
Bieber who is the head of development there.

You can reach their support desk with live chat from their site or just by
emailing support@payfast.co.za

Sorry I can't help more,

**Comment by TomFX** [comment]
Hi,

Thank you for getting back to me I really appreciate it, at the moment busy with PayFast to sort out jcart for implementation

have a super great day

Regards,

Tom
